server:
  port: 8100

exchange:
  base: "usd"
  apiUrl: "https://openexchangerates.org/api"
  apiKey: ""
gifs:
  apiUrl: "https://api.giphy.com/v1/gifs"
  gifUrl: "https://media.giphy.com/media"
  apiKey: ""
  equalValuesGifId: "3DONeV4N5Qz3gIpOue"
  errorGifId: "Vu7FU5T4RJPo1esgna"